### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by zsusswein**
This PR does a couple things:

1. Sets up a basic Dockerfile. As we discussed, it isn't quite right (conda env yaml still needs work, tests aren't totally passing) but I think it's a good first crack.
2. Set up the "database" insert script. I made the executive decision that it'll be easier if our database is just parquet files in a reasonable directory structure on S3. That way any post-processing with Spark should be dead simple. This is still missing read/wrangle/insert of metadata on the _run_ (not just the sample) but that would require shifting to (in my order of preference) a config file we can save as a table (preferably I think?), switching to json, or just tossing the existing yaml into S3.

It would be great to get thoughts/revisions/sign off on both.

### CODE REVIEW

**Comment by degregory** [comment]
First questions of undoubtedly many:  
This Dockerfile currently lets you successfully build a successfully image?
For me it fails when attempting to run the pipeline as it can't make the fastp env when running snakefile2.  The base snakemake image seems to have been recently updated, so that might be the issue.
Do all the test pass for you when you run pytest not in the docker image?  The lineage unit test was failing for me.  I figured out the fix for it, but want to see if things are behaving the same for both of us.

**Comment by zsusswein** [comment]
Yes -- it does let me build and run the image. That seems like it could be the source of the problem, but I think it's more likely you're not pulling the latest image (assuming you're using the pre-built image on Docker Hub not trying to build yourself from the Dockerfile.

And, no the tests weren't all passing but I didn't look to hard into figuring out the issue.

**Comment by degregory** [comment]
I was building from the Dockerfile.  Do you have a link where I could get the pre-built image?

**Comment by zsusswein** [comment]
Can you give `docker pull zsusswein/SHED:latest` a try?

**Comment by degregory** [comment]
I have everything working on my end now.  The exception being insert_to_db.py, which fails b/c I don't have the keys.  It looks like you've got it set to pull the keys from the os env.  I think it might be better, especially for a public docker image, to have the keys inputted via stdin.

All the tests now pass in a newly built docker image.  I had to change back conda channel priority to false to allow snake make to properly build all the envs it needs.  I think a better solution would be what I did with the docker image I built for databricks, and just have the docker image have all the tools the pipeline needs so snakemake doesn't have to handle building any of its own envs.  What are your thoughts on that?

As far as the env you have conda making for the current image, I see some things are necessary for insert_to_db.py and assume others are for other tasks you have planned?  

Regarding the single snakemake file, there are/were some shortcoming of snakemake (which might have been fixed in newer version) that led me to make the 3 files.  I can look into this again, but before doing much with the pipeline, I think we need to figure out the best strategy for parallel processing.  That conversation might merit a zoom.  But if you already have something in mind I can just start working at getting the pipeline compatible.

Do you want me to just push the updates I have to get things working?

Let me know if I missed anything.

**Comment by zsusswein** [comment]
Ok going in order:

1. I checked with our devs and they say that, under the assumption we're running this through AWS, it'll be most secure to expose the keys via env vars. We can just set them from the AWS control panel. I hear you though that we should triple check this before deploying.
2. Awesome, thank you! I'd say please do here whatever it was you did for that image. I didn't go back to your image to pull in all your tricks, but I should have.
3. I don't think I meant to put anything in the conda env yaml that wasn't being used. I basically just went into the image, manually installed everything the pipeline was using, and then copied that env to a file. It's super janky, but the only way I could get something with versions because the image is linux and I'm on a Mac.
4. Sorry, I didn't mean to include that file. It was a WIP from the first time I was trying to get things working. I'll remove it.
5. Please do!

Only other thing is that I'd love your thoughts on is: what should go in a "run metadata file". I assume we want everything in the yaml plus probably freya version? Do you know an easy way to pull that out of the existing pipeline? Anything else I'm not thinking of maybe (SHED pipeline version/SHA hash)?

**Comment by degregory** [comment]
I've pushed some changes to the files for pytesting and to get the pipeline to work without updating curl from what the snakemake docker image has.  

I'm uploading the image I built and that works for me (to the extent it can w/o the aws keys).  It should be shared with you.  I'd like to see if you can load and run it before I push any changes to the Dockerfile and such.

The snakefiles would benefit from some optimization towards whatever parallelism is to be used.  Those changes probably would need to be tested when it is being run on Spark though.

Run meta probably should have versions of every primary component used.  That info should be easy to pull and/or just have a file with that info updated as we go.  As far as freyja, the lineage data it updates during the run is pulled from http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/ and https://github.com/outbreak-info/outbreak.info/tree/master/web/src/assets/genomics . I think the simplest solution for those is just have a timestamp entry for when the freyja update is run that anyone can then use to check back to what version of those data were used.  There should also probably be start:end timestamps for the pipeline in general.  Having checksums would add to peoples confidence in the pipeline's results as they are being propagated, though I usually see them on a per file basis.  I think that would be everything someone would need to reproduce/verify the results.

**Comment by degregory** [comment]
Some more info on the docker image.  It ran the pipeline in the building and should be ready to run insert_to_db.py, though you'd need to put the keys into the evn for it to work.

**Comment by zsusswein** [comment]
@rkassa everything should be here!

**Comment by zsusswein** [comment]
Hey @degregory -- working on this a little more. Can you clear up something for me:

Do you know how freyja pulls the data? Does it do a fresh pull from those two sources each time it's run, does it download the data at install, or is there a freyja version update each time the lineage data change? I'm trying to think through how to best record this info (and whether it's worth recording the actual lineages available to freyja at the point in time). I feel like it might be too much work, but not sure how hard it is.

**Comment by degregory** [comment]
It comes with a version of the lineage data when it is installed/downloaded.  To update it requires running the update command.  That is a step in snakefile3 that is run dependent on the enable/disable setting in the yaml.   It wouldn't be difficult to just copy the files it used, but I don't know how much value that would add.

**Comment by zsusswein** [comment]
Ok @degregory -- good news & bad news.

Good: I have a basic working version of the pipeline run metadata set up. Take a quick look at it for me?

Bad: Trying to build the image throws:
```
Creating conda environment envs/fastp.yaml...
#16 1447.8 Downloading and installing remote packages.
#16 1451.3 CreateCondaEnvironmentException:
#16 1451.3 Could not create conda environment from /tmp/repo/envs/fastp.yaml:
#16 1451.3 Command:
#16 1451.3 mamba env create --quiet --file "/tmp/repo/.snakemake/conda/f0e199262dec33bd36733a39da24c31a_.yaml" --prefix "/tmp/repo/.snakemake/conda/f0e199262dec33bd36733a39da24c31a_"
#16 1451.3 Output:
#16 1451.3 Encountered problems while solving:
#16 1451.3   - package fastp-0.23.2-hd36eab0_1 requires libdeflate >=1.9,<1.10.0a0, but none of the providers can be installed
```

I'm guessing this is because something somewhere was updated and now conda is angry about it, but I'm not sure. If you're stumped too, I'll dig into it some more on my own. But I wanted to check if you had any ideas first.

**Comment by degregory** [comment]
Did the image I shared work for  you?  I wanted to make sure it did before I pushed the changes that should resolve that error.  I'll look over the other changes sometime today or tomorrow.

**Comment by degregory** [comment]
I pushed some changes to the dockerfile.  They are what worked for me before.  I don't know if they'd still work, b/c testing them with the updated config.yaml bricked my linux subsystem.  I also made some changes to the insert_to_db.py so it will work w/o the keys, for it to output the various metadata locally, and I also made some changes to the summarized lineage gathering regex.  The output I was getting was a bit off.  
While working to timestamp the freyja updating, I discovered that the recent snakemakes error when they try to do the freyja update.  It looks like the freyja developers are working on a fix for it, but at the moment, if we try to use the update command it won't work.  There are some possible work arounds that'll I'll try once I have my subsystem functional again.

**Comment by degregory** [comment]
Back up and running.  To get the docker image to build, I also had to comment out the yaml install.  I think for the pip install we'd need pyyaml, which is already present from the snakemake image.

**Comment by zsusswein** [comment]
Just tried to `docker load` the image you shared. It throws a `Error processing tar file(exit status 1): write /tmp/repo/sratoolkit.3.0.0-ubuntu64/bin/test-sra.3.0.0: no space left on device`. A little odd because I gave 250 GB of space available.

I'm pulling now and going try to build the image with your new changes.

**Comment by zsusswein** [comment]
Ok built with the changes you pushed. Everything builds and runs but I'm getting about half the tests failing:

```
(snakemake) root@3b50dc299b1f:/tmp/repo# pytest
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-7.2.0, pluggy-1.0.0
rootdir: /tmp/repo
collected 11 items                                                             

tests/test_aggregate.py .                                                [  9%]
tests/test_consensus.py .                                                [ 18%]
tests/test_download_sra.py .                                             [ 27%]
tests/test_full.py .                                                     [ 36%]
tests/test_get_fastqs.py .                                               [ 45%]
tests/test_lineages.py F                                                 [ 54%]
tests/test_mapping.py F                                                  [ 63%]
tests/test_primer_trim.py F                                              [ 72%]
tests/test_quality_check.py F                                            [ 81%]
tests/test_sam2bam.py F                                                  [ 90%]
tests/test_vc.py F                                                       [100%]

=================================== FAILURES ===================================
```

I've pushed the latest build so you can take a look. If you want, I'm happy to merge this PR as is and we can deal with whatever the issue is with these in another branch/PR.

**Comment by degregory** [comment]
I pulled the new image and all the pytests work for me.  So troubleshooting what's going on will probably be rather time consuming.  I'm fine with punting on it for now.

**Comment by zsusswein** [comment]
Ok looking through the errors a bit more, it seems like it's coming from an issue writing to disk -- doesn't seem real to me. Agreed on punting.

**Comment by zsusswein** [comment]
@degregory -- you're the reviewer. When you get the chance, can you approve and merge the PR?

**Review by degregory — APPROVED** [review]

**Comment by degregory** [comment]
Approved.  Still needs Robel's.  It looks like the .pre-comit-config.yaml needs to be pushed for the pull.  Have you updated it any on your end, or can the one from DAGdev be copied over?

**Comment by zsusswein** [comment]
cc: @rkassa -- pending your ok.

**Review by rkassa — APPROVED** [review]
LGTM 🎉 

Same question as @degregory re: .pre-commit-config.yaml, though.

**Pull request merged**
